// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e72cd051435a0d2 "Artemis (copy)", do not edit manually */
"use client";

// virtual:footer
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gMDus1vWiPay38rMR4xQ/2mM39jS82JjyysQHZrIS/icBMZ_p3_.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/HYcHVPAbe8jLEeU7c4mp/QiycTxX7vdblEOi3o00G/Time.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	RenderTarget,
	useLocaleCode,
} from "unframer";
import {
	startTransition,
	useCallback,
	useEffect,
	useRef,
	useState,
} from "react";
var fontStack = `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`;
function formatTimeOrDate(
	outputType,
	{ showYear, showMonth, showWeekday, showMinutes, showSeconds },
	timeFormat,
	monthFormat,
	localCode,
) {
	const date = /* @__PURE__ */ new Date();
	const onlyYearIsShown = !showWeekday && !showMonth && showYear;
	switch (outputType) {
		case "date":
			return new Intl.DateTimeFormat(localCode, {
				weekday: showWeekday ? "long" : void 0,
				day: onlyYearIsShown ? void 0 : "numeric",
				month: showMonth ? monthFormat : void 0,
				year: showYear ? "numeric" : void 0,
			}).format(date);
		case "time":
			return new Intl.DateTimeFormat(localCode, {
				hour: "numeric",
				minute: showMinutes ? "numeric" : void 0,
				second: showSeconds && showMinutes ? "numeric" : void 0,
				hour12: timeFormat === "12h",
			}).format(date);
		default:
			return new Intl.DateTimeFormat(localCode).format(date);
	}
}
var defaultProps = {
	height: 20,
	width: 140,
	outputType: "time",
	color: "#999",
	timeFormat: "24h",
	showYear: true,
	showMonth: true,
	showWeekday: true,
	showMinutes: true,
	showSeconds: true,
	monthFormat: "long",
	alignment: "center",
};
function Time(props) {
	const mergedProps = {
		...defaultProps,
		...props,
	};
	const {
		outputType,
		timeFormat,
		showYear,
		showMonth,
		showWeekday,
		// showHours,
		showMinutes,
		showSeconds,
		monthFormat,
		color,
		font,
		tabularFont,
	} = mergedProps;
	const localCode = useLocaleCode();
	const getTextContent = useCallback(
		() =>
			formatTimeOrDate(
				outputType,
				{
					showYear,
					showMonth,
					showWeekday,
					// showHours,
					showMinutes,
					showSeconds,
				},
				timeFormat,
				monthFormat,
				localCode,
			),
		[
			localCode,
			monthFormat,
			outputType,
			showMinutes,
			showMonth,
			showSeconds,
			showWeekday,
			showYear,
			timeFormat,
		],
	);
	const timeoutRef = useRef();
	const updateCountdown = useCallback(
		(node) => {
			if (node === null) {
				clearTimeout(timeoutRef.current);
				return;
			}
			let prev;
			const tick = () => {
				const date = /* @__PURE__ */ new Date();
				const next =
					/* @__PURE__ */ new Date().setSeconds(date.getSeconds() + 1, 0) -
					+date;
				timeoutRef.current = setTimeout(tick, next);
				const textContent = getTextContent();
				if (prev !== textContent) {
					node.textContent = textContent;
					prev = textContent;
				}
			};
			tick();
		},
		[getTextContent],
	);
	const [visible, setIsVisible] = useState(false);
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	useEffect(() => {
		startTransition(() => setIsVisible(true));
		if (isCanvas) return;
	}, [isCanvas]);
	return (
		<p
			suppressHydrationWarning={true}
			style={{
				margin: 0,
				padding: 0,
				color,
				fontFamily: fontStack,
				fontWeight: 500,
				fontSize: 16,
				lineHeight: 1,
				visibility: visible ? "visible" : "hidden",
				...font,
				fontVariantNumeric: tabularFont ? "tabular-nums" : "normal",
				whiteSpace: "nowrap",
			}}
			ref={isCanvas ? void 0 : updateCountdown}
		>
			{getTextContent()}
		</p>
	);
}
Time.displayName = "Time & Date";
addPropertyControls(Time, {
	outputType: {
		title: "Type",
		type: ControlType.Enum,
		displaySegmentedControl: true,
		options: ["date", "time"],
		optionTitles: ["Date", "Time"],
		defaultValue: defaultProps.outputType,
	},
	showWeekday: {
		title: "Day",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showWeekday,
		hidden: (props) => props.outputType !== "date",
	},
	showMonth: {
		title: "Month",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showMonth,
		hidden: (props) => props.outputType !== "date",
	},
	monthFormat: {
		title: "Format",
		type: ControlType.Enum,
		options: ["short", "long", "numeric"],
		optionTitles: ["Short", "Long", "Numeric"],
		defaultValue: defaultProps.monthFormat,
		hidden: (props) => props.outputType !== "date" || !props.showMonth,
	},
	showYear: {
		title: "Year",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showYear,
		hidden: (props) => props.outputType !== "date",
	},
	timeFormat: {
		title: "Format",
		type: ControlType.Enum,
		options: ["12h", "24h"],
		optionTitles: ["12h", "24h"],
		displaySegmentedControl: true,
		defaultValue: defaultProps.timeFormat,
		hidden: (props) => props.outputType !== "time",
	},
	// showHours: {
	//     title: "Hours",
	//     type: ControlType.Boolean,
	//     enabledTitle: "Show",
	//     disabledTitle: "Hide",
	//     defaultValue: defaultProps.showHours,
	//     hidden: (props) => props.outputType !== "time",
	// },
	showMinutes: {
		title: "Minutes",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showMinutes,
		hidden: (props) => props.outputType !== "time",
	},
	showSeconds: {
		title: "Seconds",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: defaultProps.showSeconds,
		hidden: (props) => props.outputType !== "time" || !props.showMinutes,
	},
	font: {
		type: ControlType.Font,
		controls: "extended",
	},
	tabularFont: {
		title: "Tabular",
		type: ControlType.Boolean,
		defaultValue: true,
	},
	color: {
		type: ControlType.Color,
		defaultValue: defaultProps.color,
	},
});

// /:https://framerusercontent.com/modules/9tbleeARZKK4WCyVTUSl/uZcRDllF2DJwDgDZAS1w/R4bJKYfBm.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;DM Sans-regular",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
				weight: "400",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v16/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-JDW32RmYJpso5.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	'.framer-mMexl .framer-styles-preset-1yg8h9f:not(.rich-text-wrapper), .framer-mMexl .framer-styles-preset-1yg8h9f.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.1px; --framer-line-height: 1.3em; --framer-paragraph-spacing: 16px; --framer-text-alignment: left; --framer-text-color: var(--token-0ba7cc43-9dd6-43f5-bf85-fd56e07a2fea, #2a3132); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-mMexl .framer-styles-preset-1yg8h9f:not(.rich-text-wrapper), .framer-mMexl .framer-styles-preset-1yg8h9f.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.3em; --framer-paragraph-spacing: 16px; --framer-text-alignment: left; --framer-text-color: var(--token-0ba7cc43-9dd6-43f5-bf85-fd56e07a2fea, #2a3132); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-mMexl .framer-styles-preset-1yg8h9f:not(.rich-text-wrapper), .framer-mMexl .framer-styles-preset-1yg8h9f.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.4em; --framer-paragraph-spacing: 16px; --framer-text-alignment: left; --framer-text-color: var(--token-0ba7cc43-9dd6-43f5-bf85-fd56e07a2fea, #2a3132); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-mMexl";

// /:https://framerusercontent.com/modules/6i7k1RqRuucauRXYz9fm/WxqhvUXm0tj1dSTE635Y/h6pWTosdp.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var enabledGestures = {
	MqlpH4m9T: {
		hover: true,
		pressed: true,
	},
};
var serializationHash = "framer-y0rCm";
var variantClassNames = {
	MqlpH4m9T: "framer-v-14ziea2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, width, ...props }) => {
	return {
		...props,
		jU4lyVxrL: link ?? props.jU4lyVxrL,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		jU4lyVxrL,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "MqlpH4m9T",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={jU4lyVxrL}
						motionChild={true}
						nodeId={"MqlpH4m9T"}
						scopeId={"h6pWTosdp"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-14ziea2", className2, classNames)} framer-wtx01l`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"MqlpH4m9T"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"MqlpH4m9T-hover": {
										"data-framer-name": void 0,
									},
									"MqlpH4m9T-pressed": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-hw9tkp"}
								data-framer-name={"Name"}
								fonts={[
									"GF;Libre Baskerville-regular",
									"GF;Libre Baskerville-italic",
								]}
								layoutDependency={layoutDependency}
								layoutId={"Lij1tbhQV"}
								style={{
									"--extracted-2gxw0f":
										"var(--token-a2418e68-b41d-46d1-9e27-1a488bd30077, rgb(255, 89, 0))",
									"--extracted-r6o4lv":
										"var(--token-a2418e68-b41d-46d1-9e27-1a488bd30077, rgb(255, 89, 0))",
									"--framer-paragraph-spacing": "0px",
									scale: 1,
								}}
								variants={{
									"MqlpH4m9T-hover": {
										scale: 1.04,
									},
									"MqlpH4m9T-pressed": {
										scale: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector":
												"R0Y7TGlicmUgQmFza2VydmlsbGUtcmVndWxhcg==",
											"--framer-font-family":
												'"Libre Baskerville", "Libre Baskerville Placeholder", serif',
											"--framer-font-size": "24px",
											"--framer-letter-spacing": "0px",
											"--framer-line-height": "110%",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a2418e68-b41d-46d1-9e27-1a488bd30077, rgb(255, 89, 0)))",
										}}
									>
										{"Artemis "}
										<motion.span
											style={{
												"--font-selector":
													"R0Y7TGlicmUgQmFza2VydmlsbGUtaXRhbGlj",
												"--framer-font-style": "italic",
											}}
										>
											{"&"}
										</motion.span>
									</motion.p>
									<motion.p
										style={{
											"--font-selector": "R0Y7TGlicmUgQmFza2VydmlsbGUtaXRhbGlj",
											"--framer-font-family":
												'"Libre Baskerville", "Libre Baskerville Placeholder", serif',
											"--framer-font-size": "24px",
											"--framer-font-style": "italic",
											"--framer-letter-spacing": "0px",
											"--framer-line-height": "110%",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-2gxw0f, var(--token-a2418e68-b41d-46d1-9e27-1a488bd30077, rgb(255, 89, 0)))",
										}}
									>
										{"   Artemis"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-y0rCm.framer-wtx01l, .framer-y0rCm .framer-wtx01l { display: block; }",
	".framer-y0rCm.framer-14ziea2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 80px; justify-content: center; overflow: visible; padding: 24px; position: relative; text-decoration: none; width: min-content; }",
	".framer-y0rCm .framer-hw9tkp { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
var Framerh6pWTosdp = withCSS(Component, css2, "framer-y0rCm");
var stdin_default = Framerh6pWTosdp;
Framerh6pWTosdp.displayName = "Logo";
Framerh6pWTosdp.defaultProps = {
	height: 80,
	width: 174,
};
addPropertyControls2(Framerh6pWTosdp, {
	jU4lyVxrL: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts(
	Framerh6pWTosdp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Libre Baskerville",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/librebaskerville/v16/kmKnZrc3Hgbbcjq75U4uslyuy4kn0pNbYRI4CN2V.woff2",
					weight: "400",
				},
				{
					family: "Libre Baskerville",
					source: "google",
					style: "italic",
					url: "https://fonts.gstatic.com/s/librebaskerville/v16/kmKhZrc3Hgbbcjq75U4uslyuy4kn0qNcaxMaDc2V2ro.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/gMDus1vWiPay38rMR4xQ/2mM39jS82JjyysQHZrIS/icBMZ_p3_.js
var LogoFonts = getFonts(stdin_default);
var TimeDateFonts = getFonts(Time);
var serializationHash2 = "framer-ayZQQ";
var variantClassNames2 = {
	PQQN3q0_1: "framer-v-712aqk",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "PQQN3q0_1",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.footer
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-712aqk",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"PQQN3q0_1"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "GvB3jHHOH",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider
									height={80}
									width={"136px"}
									y={
										(componentViewport?.y || 0) +
										8 +
										(((componentViewport?.height || 117) - 16 - 100.8) / 2 +
											0 +
											0)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-7vpb76-container"}
										layoutDependency={layoutDependency}
										layoutId={"ithOcaSgs-container"}
										nodeId={"ithOcaSgs"}
										rendersWithMotion={true}
										scopeId={"icBMZ_p3_"}
									>
										{_jsx3(stdin_default, {
											height: "100%",
											id: "ithOcaSgs",
											jU4lyVxrL: resolvedLinks[0],
											layoutId: "ithOcaSgs",
											style: {
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</ResolveLinks>
						<motion2.div
							className={"framer-1rxo6aj"}
							data-framer-name={"Copyright"}
							layoutDependency={layoutDependency}
							layoutId={"OPsarDm1u"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-hrre3b"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Xs63zrN2r"}
								style={{
									"--extracted-tcooor":
										"var(--token-5dfdec3b-3139-426d-b9fc-d1b5ecf28487, rgb(95, 101, 102))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.div
										className={"framer-styles-preset-1yg8h9f"}
										data-styles-preset={"R4bJKYfBm"}
										style={{
											"--framer-text-color":
												"var(--extracted-tcooor, var(--token-5dfdec3b-3139-426d-b9fc-d1b5ecf28487, rgb(95, 101, 102)))",
										}}
									>
										{"\xA9"}
									</motion2.div>
								</React2.Fragment>
							</RichText2>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1jekgrd-container"}
									data-framer-name={"Current year"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"MebkcVFpV-container"}
									name={"Current year"}
									nodeId={"MebkcVFpV"}
									rendersWithMotion={true}
									scopeId={"icBMZ_p3_"}
								>
									<Time
										color={
											"var(--token-5dfdec3b-3139-426d-b9fc-d1b5ecf28487, rgb(95, 101, 102))"
										}
										font={{
											fontFamily:
												'"DM Sans", "DM Sans Placeholder", sans-serif',
											fontSize: "16px",
											fontStyle: "normal",
											fontWeight: 400,
											letterSpacing: "0em",
											lineHeight: "1.3em",
										}}
										height={"100%"}
										id={"MebkcVFpV"}
										layoutId={"MebkcVFpV"}
										monthFormat={"long"}
										name={"Current year"}
										outputType={"date"}
										showMinutes={true}
										showMonth={false}
										showSeconds={true}
										showWeekday={false}
										showYear={true}
										tabularFont={false}
										timeFormat={"24h"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
					</motion2.footer>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ayZQQ.framer-1jwkjpf, .framer-ayZQQ .framer-1jwkjpf { display: block; }",
	".framer-ayZQQ.framer-712aqk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; }",
	".framer-ayZQQ .framer-7vpb76-container { flex: none; height: auto; position: relative; width: 136px; }",
	".framer-ayZQQ .framer-1rxo6aj { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }",
	".framer-ayZQQ .framer-hrre3b { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ayZQQ .framer-1jekgrd-container { flex: none; height: auto; position: relative; width: auto; }",
	...css,
];
var FramericBMZ_p3_ = withCSS2(Component2, css3, "framer-ayZQQ");
var stdin_default2 = FramericBMZ_p3_;
FramericBMZ_p3_.displayName = "Footer";
FramericBMZ_p3_.defaultProps = {
	height: 117,
	width: 152,
};
addFonts2(
	FramericBMZ_p3_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "DM Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Sans",
					url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAopxhS2f3ZGMZpg.woff2",
					weight: "400",
				},
			],
		},
		...LogoFonts,
		...TimeDateFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	GvB3jHHOH: {
		path: "/",
	},
	HgjcxtZBK: {
		path: "/works",
	},
	MZ_pihJ7J: {
		path: "/works/:slug",
	},
	ah06aYHLl: {
		path: "/404",
	},
	gnXX0HZW8: {
		path: "/playground",
	},
};

// virtual:footer
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e72cd051435a0d278f79c2f335256970abe9e403cd7a9fb766ef95df43befbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e72cd051435a0d278f79c2f335256970abe9e403cd7a9fb766ef95df43befbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
